

#define USING_AU_STRING_CVT 
#define USING_AU_COLOR
#define USING_AU_TIMER
#define USING_AU_FILE_SYSTEM
#define USING_AU_PTR
#define USING_AU_LOGGER
#define USING_AU_TYPES
#define USING_AU_EXCEPTION
#define USING_AU_MATH
#define USING_AU_THREAD
#define USING_AU_INI
#define USING_AU_PARALLEL_FOR
#define USING_AU_COMMAND_LINE